# 环境配置

## 安装conda

In [1]:
# https://blog.csdn.net/weixin_43840215/article/details/89599559
!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

--2020-08-18 20:22:58--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
正在解析主机 repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c84f, ...
正在连接 repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [跟随至新的 URL]
--2020-08-18 20:23:02--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
正在解析主机 repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
正在连接 repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：93052469 (89M) [application/x-sh]
正在保存至: “Miniconda3-latest-Linux-x86_64.sh”

16% [=====>                                 ] 15,456,713   246KB/s 剩余 3m 48s   ^C


In [ ]:
!chmod 777 Miniconda3-latest-Linux-x86_64.sh
!sh Miniconda3-latest-Linux-x86_64.sh

In [6]:
# 上面链接都是https的。然而我在下载的时候报错了。应该把s删掉
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
!conda config --set show_channel_urls yes 
!conda config --get channels

/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令


In [ ]:
# https://blog.csdn.net/zzq060143/article/details/88042075
# 请仔细参考这个，添加镜像
!conda install pytorch torchvision cudatoolkit=10.2

In [23]:
import sys

sys.executable

'/root/miniconda3/bin/python'

In [3]:
import torch

In [ ]:
# 由于我是使用conda安装的，默认使用的是conda的base环境。
# 所以其他环境是使用不了torch的
# 先要激活conda环境，并且退出当前的virtualenv

!deactivate # 在当前环境直接输入这个指令即可
!source miniconda3/bin/activate
!conda jupyter notebook

In [2]:
import pandas as pd

import numpy as np

In [24]:
data = pd.DataFrame(np.arange(8).reshape(4,2),columns=['a','b'])

In [12]:
test = pd.DataFrame(np.arange(4,12).reshape(4,2),columns=['c','d'])

In [18]:
# 可以使用这种方法同时修改训练集和测试集
all_data = [data, test]
for i in all_data:
    i.iloc[:,1] = np.arange(4)

In [30]:
# 查看电脑的显卡能不能使用
torch.cuda.is_available()

False

# 两个重要函数

In [32]:
# dir(torch) dir可以查看有哪些可用的函数

In [33]:
# help(torch.cuda) help告诉我们如何使用这个函数

# torch的学习

In [4]:
# torch类型数据
# numpy类型数据

np_data = np.arange(8).reshape(2,4)
np_data

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## 数据类型

在torch中，如果是一个数字，就是0维，**在torch中没有string类型的数据**。如果要表示字符串类型，可以使用one-hot方法

然而在实际的生活中，英语单词有上万多个，我们单独靠one-hot，会使得矩阵非常稀疏。而且不能表达出单词的近似程度。

所以one-hot编码是有缺陷的，所以人们开发出来其他的方式来编码，编码叫Embedding， 里面有w2v， glove方式

floattensor  32

doubletensor 64

longtensor 64

inttensor 32

bytetensor 8

In [81]:
a = torch.randn(2,3)
a.type() # 返回的是具体的数据类型

'torch.FloatTensor'

In [82]:
# 返回的是基本的数据类型
type(a)

torch.Tensor

In [83]:
# 判断诗句类型是不是一致
isinstance(a, torch.FloatTensor)

True

In [ ]:
# 将数据放到GPU的时候数据类型但是又会发生变化

isinstance(data, torch.cuda.FloatTensor)

data.cuda() # 将数据放到GPU上

isinstance(data, torch.cuda.FloatTensor)

0维的有什么用呢？通常loss就是0维的，也就是标量

In [86]:
# 纬度为0的标量，维度为0就是标量
torch.tensor(1.)

tensor(1.)

In [87]:
torch.tensor(1.).item()

1.0

In [88]:
torch.tensor(1.).shape

torch.Size([])

In [89]:
torch.tensor(1.).dim()

0

维度为1的张量有什么用呢？

在神经元中，我们通常要设置偏置。ax+b中b就是。我们用一维张量表示

In [92]:
# 1 dim []
torch.tensor([1])

tensor([1])

In [94]:
torch.tensor([1]).shape

torch.Size([1])

In [95]:
torch.tensor([1,1]).item()

ValueError: only one element tensors can be converted to Python scalars

In [97]:
# 2 dim [[],[]],多个列表嵌套就是2维

a = torch.FloatTensor(2,3)
a

tensor([[-1.0798e-24,  4.5891e-41, -1.5148e+00],
        [ 3.0624e-41,         nan,  0.0000e+00]])

In [103]:
b = torch.FloatTensor(1,3) # 注意这是随机生成的
b

tensor([[-1.0798e-24,  4.5891e-41, -1.3108e+00]])

In [106]:
# 3 dim [[[]],[[]]]
# 3 dim有什么用呢？他们的使用场景非常广泛
# 比如在nlp中，一句话有10个单词，每个单词用向量表示这句话就可以用2维tensor表示[10, 100]/假如每个单词用100个表示
# 假如现在有20句话，用3 dim表示[20,10,100]
c = torch.FloatTensor(1,2,3)
c

tensor([[[-1.0798e-24,  4.5891e-41, -1.5225e+00],
         [ 3.0624e-41,  4.4842e-44,  0.0000e+00]]])

In [107]:
c[0]

tensor([[-1.0798e-24,  4.5891e-41, -1.5225e+00],
        [ 3.0624e-41,  4.4842e-44,  0.0000e+00]])

In [109]:
c[0][0]

tensor([-1.0798e-24,  4.5891e-41, -1.5225e+00])

In [110]:
# 更高维 4dim，5dim
# [2,3,29,29]
# 上面2表示照片数量，3表示每个照片颜色通道RGB，29*29表示长宽
# 注意一个维度，只能用来描述一种特征

## 创建tensor

In [ ]:
# 未初始化的tensor，不要直接使用未初始化的数据，输入到其他地方
# 未初始化只是为了申请内存，然后赋值给他。
# 如果直接将未初始化的数据喂到其他地方。因为值是随机的。有些值是无穷大。容易出现问题

torch.FloatTensor(2,2,2) # 未初始化的数据，其内部的值是随机的

In [111]:
# 随机初始化
torch.rand(3,3) # 初始化的值是在0-1之间

tensor([[0.8526, 0.3177, 0.6964],
        [0.0450, 0.3220, 0.9346],
        [0.5983, 0.3297, 0.9744]])

In [114]:
a = torch.rand(3,3,3)
c = torch.rand_like(a) # 读取一个tensor的shape，然后传给rand like。like相似
c

tensor([[[0.4837, 0.7445, 0.2592],
         [0.3884, 0.1026, 0.6049],
         [0.4994, 0.7637, 0.4178]],

        [[0.3952, 0.8937, 0.4947],
         [0.4957, 0.4705, 0.9129],
         [0.7484, 0.5479, 0.8227]],

        [[0.6375, 0.6115, 0.6347],
         [0.4693, 0.2609, 0.5884],
         [0.2203, 0.5070, 0.4755]]])

In [116]:
torch.randint(1,10,[2,2]) # 在最大和最小值区间生成随机数，第三个参数是指定shape，以列表的形式传入，不包括最大值10

tensor([[2, 9],
        [3, 9]])

In [118]:
torch.randn(3,3) # 生成一个正太分布的数据。

tensor([[-0.8897,  1.5054,  0.1210],
        [-0.1361,  0.3104, -0.7207],
        [ 1.0253, -1.2426,  0.5322]])

In [126]:
torch.full([2,3],0.0,) # 好像只能生成float类型的数据

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [129]:
torch.full([],3.) # 创建一个标量

tensor(3.)

In [134]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [137]:
torch.linspace(0,10,10) # 等份切

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [138]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [139]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [140]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [141]:
torch.randperm(10) # 生成一个随机的序列

tensor([2, 4, 3, 1, 8, 0, 7, 6, 9, 5])

## 索引和切片

In [145]:
data = torch.rand(2,3,2)
data

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]],

        [[0.7212, 0.0430],
         [0.5839, 0.6931],
         [0.6613, 0.2377]]])

In [146]:
data[0] # 索引的是第0个3，2

tensor([[0.9975, 0.8395],
        [0.4927, 0.9900],
        [0.3013, 0.9192]])

In [149]:
data[0,0]

tensor([0.9975, 0.8395])

In [148]:
data[0,0,1]

tensor(0.8395)

In [147]:
for each in data: # 居然可以遍历
    print(each)

tensor([[0.9975, 0.8395],
        [0.4927, 0.9900],
        [0.3013, 0.9192]])
tensor([[0.7212, 0.0430],
        [0.5839, 0.6931],
        [0.6613, 0.2377]])


In [153]:
# 切片
data[:1]

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]]])

In [154]:
data[:1].dim() # 依旧是三维的 # 这里是对第一个通道索引

3

In [157]:
data[:1,:1] # 还可以对第二个通道索引

tensor([[[0.9975, 0.8395]]])

In [158]:
data[:1,-1:] # -1开始表示只选取末尾

tensor([[[0.3013, 0.9192]]])

In [160]:
data[:1:2,:,:] # 甚至可以隔行采样

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]]])

In [162]:
data = torch.rand(3,3,3)
data

tensor([[[0.9250, 0.9249, 0.6874],
         [0.3065, 0.2696, 0.8503],
         [0.0577, 0.7079, 0.6500]],

        [[0.1635, 0.2214, 0.2830],
         [0.1326, 0.0176, 0.5144],
         [0.7082, 0.1147, 0.5520]],

        [[0.0726, 0.4157, 0.1398],
         [0.6775, 0.5979, 0.3828],
         [0.5380, 0.3950, 0.5863]]])

In [163]:
data.index_select(0,[0,2])

TypeError: index_select() received an invalid combination of arguments - got (int, list), but expected one of:
 * (name dim, Tensor index)
      didn't match because some of the arguments have invalid types: (int, list)
 * (int dim, Tensor index)
      didn't match because some of the arguments have invalid types: (int, list)


In [172]:
# torch.select_index用法
test = torch.linspace(1,12, 12).view(3,4)
test

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [175]:
test.index_select(1, torch.tensor([0,1])) # https://blog.csdn.net/g_blink/article/details/102854188

# 参数说明：第一个参数0表示按行索引，1表示按列索引。第二个参数传入一个tensor，表示传入的index

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [178]:
test[...] # 三个句号表示所有维度都取。:::替代这个

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [177]:
test[1,...] # 可以先给定一个维度

tensor([5., 6., 7., 8.])

In [179]:
test[...,::2] # 也可以这样混合着使用

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])

In [181]:
# 设置阈值，将大于阈值的位置设置为1

x = torch.randn(3,4)
x

tensor([[ 1.3531,  0.2694, -0.6561,  0.3088],
        [ 0.9426, -0.3599, -0.1596, -1.0377],
        [-0.4034,  1.9707,  0.0576,  0.8735]])

In [182]:
x.ge(0.5) # 设置阈值，大于阈值的返回true

tensor([[ True, False, False, False],
        [ True, False, False, False],
        [False,  True, False,  True]])

## tensor维度增加

In [192]:
# view，reshape
# 这里举例为minist手写数据集。4表示4张图片，3表示颜色只有RGB。28*28表示长宽
test = torch.rand(4,3,28,28) # rand生成的数是在0-1之间

In [193]:
test.shape

torch.Size([4, 3, 28, 28])

In [198]:
# 第一个view操作，合并维度

res = test.view(4,3*28*28) # 把后面几个维度合并，特别适合神经网络中的全连接层

In [196]:
res.shape

torch.Size([4, 2352])

In [200]:
res

tensor([[0.1116, 0.5150, 0.2852,  ..., 0.7692, 0.9233, 0.0275],
        [0.7971, 0.8134, 0.7538,  ..., 0.2127, 0.4565, 0.0840],
        [0.6096, 0.0647, 0.9465,  ..., 0.7477, 0.9180, 0.1116],
        [0.2819, 0.0272, 0.8308,  ..., 0.9183, 0.9931, 0.2143]])

In [201]:
res = res.view(4,3,28,28) # 数据的恢复。可以将数据再展回去

In [202]:
# squeeze,unsqueeze

test = torch.rand(4,1,28,28)

In [203]:
test.unsqueeze(0).shape # 在0的前面插入一个维度

torch.Size([1, 4, 1, 28, 28])

In [204]:
test.unsqueeze(-1).shape # 在-1的后面插入

torch.Size([4, 1, 28, 28, 1])

In [213]:
test = torch.rand(2,2)
test

tensor([[0.1659, 0.4205],
        [0.4678, 0.1701]])

In [214]:
test.shape

torch.Size([2, 2])

In [217]:
test.unsqueeze_(0) # 只是增加了一个维度，并不改变数据本身。正数表示在0之前添加
# 加下划线表示会替换原来的变量

tensor([[[0.1659, 0.4205],
         [0.4678, 0.1701]]])

In [218]:
test.shape

torch.Size([1, 2, 2])

In [208]:
test = torch.tensor([1,2])
test

tensor([1, 2])

In [211]:
test.dim()

1

In [209]:
test.unsqueeze(-1) # 这样展开为列向量

tensor([[1],
        [2]])

维度变化的一般用处

In [223]:
test = torch.rand(3,3,12,2)
# 假如现在想在12这个维度加一个偏置
bias = torch.rand(12)

In [224]:
bias.shape

torch.Size([12])

In [225]:
# 如果直接相加的话，维度不同是不能直接相加的
bias = bias.unsqueeze(0).unsqueeze(0).unsqueeze(-1)

In [226]:
bias.shape # 后面会介绍1->3的方法。方法名叫扩张

torch.Size([1, 1, 12, 1])

## tensor维度删减

In [227]:
# squeeze
test = torch.rand(2,2,1)

In [228]:
test.shape

torch.Size([2, 2, 1])

In [232]:
test

tensor([[[0.9808],
         [0.9460]],

        [[0.1491],
         [0.1736]]])

In [231]:
test[1,...]

tensor([[0.1491],
        [0.1736]])

In [229]:
test.squeeze() # 默认是把为1的维度去掉，并不改变数据本身

tensor([[0.9808, 0.9460],
        [0.1491, 0.1736]])

In [234]:
test.squeeze(0).shape # 0位置不是1，所以不会删除维度。没有报错，返回的不变

torch.Size([2, 2, 1])

In [235]:
test.squeeze(-1).shape # 为1就删除了

torch.Size([2, 2])

## 维度拓展

In [246]:
# expend, repeat
test = torch.rand(1,32,1,1)

In [247]:
test.shape

torch.Size([1, 32, 1, 1])

In [248]:
# 假如现在要拓展为4，32，14，14

test = test.expand(4,32,14,14)

In [250]:
test.expand(5,32,14,14) # 注意，只能维度值为1的进行扩张，其他维度并不能扩张，3-5就不能，只能1-5

RuntimeError: The expanded size of the tensor (5) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [5, 32, 14, 14].  Tensor sizes: [4, 32, 14, 14]

In [253]:
test.expand(-1,32,-1,-1).shape # -1表示这个维度不变

torch.Size([4, 32, 14, 14])

In [254]:
# repeat

test = torch.rand(1,32,1,1)
test.repeat(4,1,14,14).shape # repeat4表示重复4次。32保持不变。所以是1.这里不推荐使用repeat

torch.Size([4, 32, 14, 14])

## 转置

In [255]:
test = torch.rand(2,2)

In [256]:
test.t()

tensor([[0.3665, 0.5724],
        [0.1173, 0.2822]])

In [257]:
test = torch.rand(1,2,3) # 注意只有在二维的情况下才能转置
test.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

## 交换维度

In [258]:
# transpose

test = torch.rand(1,32,1,1)

In [259]:
test.transpose(0,1).shape

torch.Size([32, 1, 1, 1])

In [260]:
# permuter

test.permute(1,2,3,0).shape # 直接传入位置即可

torch.Size([32, 1, 1, 1])

## 张量相加

现在假设有个场景，tensor+scaler

In [261]:
test = torch.rand(2,12,4) # 2个班级，每班级12名学生，每学生学4门课程得分

In [263]:
# 现在假如我要给学生的每门课程加3分
# 也就是实现张量加标量

bias = torch.tensor([3])
bias.shape

torch.Size([1])

In [265]:
bias = bias.unsqueeze(0).unsqueeze(0).expand(2,12,4)

In [267]:
bias.shape

torch.Size([2, 12, 4])

In [268]:
bias

tensor([[[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [269]:
test + bias

tensor([[[3.5926, 3.6585, 3.5626, 3.7852],
         [3.3929, 3.1034, 3.3518, 3.7314],
         [3.2450, 3.1379, 3.8641, 3.9138],
         [3.4566, 3.7594, 3.2158, 3.7839],
         [3.2208, 3.7148, 3.0081, 3.4197],
         [3.4276, 3.0490, 3.2225, 3.5248],
         [3.9596, 3.6256, 3.1139, 3.5801],
         [3.4581, 3.6182, 3.0749, 3.3375],
         [3.3139, 3.8552, 3.4132, 3.8696],
         [3.9641, 3.3554, 3.6175, 3.8541],
         [3.1284, 3.9316, 3.5702, 3.9627],
         [3.6021, 3.9347, 3.7362, 3.8569]],

        [[3.3054, 3.8866, 3.6174, 3.2519],
         [3.7663, 3.4736, 3.9203, 3.5704],
         [3.3170, 3.5279, 3.8722, 3.3639],
         [3.3188, 3.2035, 3.3834, 3.0632],
         [3.5136, 3.0656, 3.6519, 3.5914],
         [3.4435, 3.0767, 3.5103, 3.5679],
         [3.8727, 3.5434, 3.7100, 3.6311],
         [3.9628, 3.6173, 3.2581, 3.0761],
         [3.0588, 3.5210, 3.5379, 3.3656],
         [3.5046, 3.8208, 3.3258, 3.6775],
         [3.1048, 3.6571, 3.4247, 3.7635],
         

现在假设我们只给最低维度某个科目加分怎么办

In [270]:
bias = torch.tensor([0,0,2,0])
bias.shape

torch.Size([4])

In [271]:
bias = bias.unsqueeze(0).unsqueeze(0).expand(2,12,4)

In [272]:
bias

tensor([[[0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0]],

        [[0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0],
         [0, 0, 2, 0]]])

## 合并拼接

In [273]:
# cat

test1 = torch.rand(3,2,4)
test2 = torch.rand(4,2,4)
test3 = torch.rand(3,2,1)

In [278]:
torch.cat([test1,test2], dim=0).shape # 按行拼接

torch.Size([7, 2, 4])

In [279]:
torch.cat([test1,test3], dim=2).shape # cat可以选择你要的维度，dim=2表示最后面这个维度

torch.Size([3, 2, 5])

In [284]:
# stack
# stack会按指定的维度，然后创建一个新的维度


# 考虑下面的场景/一位老师统计了两个班级的成绩。现在要将两个班级的成绩合并
# 新增加的维度表示班级，0表示第一个班级，
# stack只能使用在两个tensor的shape相同的情况下
test1 = torch.rand(32,3)
test2 = torch.rand(32,3)

torch.stack([test1,test2],dim=0).shape

torch.Size([2, 32, 3])

## 数据拆分

In [293]:
# split
a1 = torch.rand(2,2,1)
a2 = torch.rand(3,2,1)

test = torch.cat([a1,a2],dim=0)
test.shape

torch.Size([5, 2, 1])

In [294]:
# 把原先cat的数据拆分出去
# 拆分成两个，按第0维度拆分，按2，3拆分
b1, b2 = test.split([2,3],dim=0)

In [296]:
b1.shape

torch.Size([2, 2, 1])

In [299]:
# 比较两个是否相等，
torch.any(torch.eq(a1,b1))

tensor(True)

In [300]:
# chunk


# chunk 是按数量拆分。4/2 = 2这种类型
test = torch.rand(4,3,2)
a, b = test.chunk(2,dim=0)

In [301]:
a.shape

torch.Size([2, 3, 2])

## 将array转化成tensor

In [5]:
 torch_data = torch.from_numpy(np_data)
torch_data # 将np数据转化成tensor

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [6]:
type(torch_data)

torch.Tensor

## 将tensor转化成array

In [7]:
tensor_to_array = torch_data.numpy()

## 一些常用函数

In [23]:
data1 = [1,9]
data2 = [[1,2],[3,4]]

In [24]:
torch.mean(data1)

TypeError: mean(): argument 'input' (position 1) must be Tensor, not list

In [25]:
np.mean(data1)

5.0

In [26]:
# 在torch和numpy中，前者最好先将数据转化成tensor的形式，后者最好转化成array的形式
# 这样转换后，才好通过运算
array1 = np.array(data1)
array2 = np.array(data2)
tensor1 = torch.FloatTensor(data1)
tensor2 = torch.FloatTensor(data2)

In [27]:
torch.mean(data)

tensor(3.)

In [28]:
torch.sin(data)

tensor([ 0.8415,  0.4121, -0.8415,  0.1411])

In [29]:
torch.abs(data)

tensor([1., 9., 1., 3.])

## tensor的基本运算

### 四则运算

In [311]:
a = torch.rand(3,2)
b = torch.rand(2)

In [312]:
a.dim()

2

In [313]:
b.dim()

1

In [314]:
a + b

tensor([[0.9876, 0.4394],
        [0.6017, 0.8031],
        [0.7488, 1.0863]])

In [315]:
# 可以看到两个add和+结果是一样的，这里建议直接使用+
torch.add(a,b)

tensor([[0.9876, 0.4394],
        [0.6017, 0.8031],
        [0.7488, 1.0863]])

In [316]:
# 为什么两个维度不一样，也可以直接相加呢？
# a的最低维度，也就是最右边是2
# b的最低维度也是2.shape是一样的
# 这是pytorch的broadcast机制。会自动拓展。使用这个机制，可以省去很多的内存
# 直接使用expand的话，会消耗很多空间

In [317]:
a - b

tensor([[ 0.1547,  0.2538],
        [-0.2312,  0.6175],
        [-0.0841,  0.9008]])

In [318]:
a * b # 相同位置进行相乘

tensor([[0.2379, 0.0322],
        [0.0772, 0.0659],
        [0.1384, 0.0922]])

In [319]:
a / b

tensor([[ 1.3716,  3.7352],
        [ 0.4449,  7.6554],
        [ 0.7980, 10.7079]])

### tensor乘法

In [320]:
# 注意这里的乘法是矩阵的乘法

# 矩阵的乘法有mm和matmul两个接口

a = torch.rand(3,4)
b = torch.rand(4,2)

torch.mm(a,b) # mm只适用于2D

tensor([[1.5968, 1.6098],
        [1.8018, 1.3237],
        [1.4462, 0.8854]])

In [321]:
# matmul适用于多维，这里推荐使用matmul
# 等价于matmul
a @ b

tensor([[1.5968, 1.6098],
        [1.8018, 1.3237],
        [1.4462, 0.8854]])

### 利用乘法进行降维

In [324]:
a = torch.rand(100,219)
b = torch.rand(10,219)

(a @ b.t()).shape # 有什么用处呢？全连接层输入是100， 最后输出神经元是10.这就是降维过程

torch.Size([100, 10])

### 多维的矩阵相乘

In [327]:
# 这里dim 1 一个是3，一个是1.维度不一样，但是也可以运算，是使用了broadcast机制
# 1会复制数据到3维，然后再相乘。

a = torch.rand(4,3,20,64)
b = torch.rand(4,1,64,32)

(a@b).shape  # 多维矩阵，可以要求最后两维的数据变化。但高维的要不变。后面两维乘法相当于2维乘法

torch.Size([4, 3, 20, 32])

### 次方运算

In [328]:
a = torch.rand(2,2)
a**2

tensor([[0.2450, 0.4258],
        [0.6737, 0.0015]])

In [329]:
a.sqrt()

tensor([[0.7035, 0.8078],
        [0.9060, 0.1963]])

### 对数运算

In [334]:
torch.exp(torch.full([2,2],1.0)) # e的1次方

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [337]:
torch.log(torch.full([3,3],4.))

tensor([[1.3863, 1.3863, 1.3863],
        [1.3863, 1.3863, 1.3863],
        [1.3863, 1.3863, 1.3863]])

## tensor裁剪

In [338]:
# clamp函数

test = torch.rand(4,4)

In [339]:
test = test*14

In [341]:
test

tensor([[ 4.2245, 13.1836,  1.0374,  7.9265],
        [ 4.7323,  3.0531,  8.0399, 11.4777],
        [ 2.6512,  2.6686,  2.9348,  8.7696],
        [11.4041, 12.8540,  2.7486,  9.6565]])

In [343]:
test.max()

tensor(13.1836)

In [344]:
test.min()

tensor(1.0374)

In [342]:
test.clamp(10) # 只传入10，表示裁剪最小值。小于10的都赋值为10

tensor([[10.0000, 13.1836, 10.0000, 10.0000],
        [10.0000, 10.0000, 10.0000, 11.4777],
        [10.0000, 10.0000, 10.0000, 10.0000],
        [11.4041, 12.8540, 10.0000, 10.0000]])

In [345]:
test.clamp(0,10) # 设置一个阈值，在0-10之间，小于0的都会赋值为0，大于10的都会赋值为10

tensor([[ 4.2245, 10.0000,  1.0374,  7.9265],
        [ 4.7323,  3.0531,  8.0399, 10.0000],
        [ 2.6512,  2.6686,  2.9348,  8.7696],
        [10.0000, 10.0000,  2.7486,  9.6565]])

## 矩阵相乘

In [30]:
array2.dot(array2) # 矩阵的乘法

array([[ 7, 10],
       [15, 22]])

In [31]:
array2.dot(array1)

array([19, 39])

In [32]:
array1*array2 # 甚至可以按位运算

array([[ 1, 18],
       [ 3, 36]])

In [36]:
tensor1

tensor([1., 9.])

In [42]:
tensor2

tensor([[1., 2.],
        [3., 4.]])

In [44]:
tensor1.dot(tensor1) # 1*1+9*9

tensor(82.)

## torch的属性统计

### 范数

In [347]:
# norm
# 可以自己设置1，2和维度

a = torch.full([8],1.)

In [348]:
b = a.view(2,4)
c = a.view(2,2,2)

In [349]:
a.norm(1)

tensor(8.)

In [350]:
b.norm(1)

tensor(8.)

In [351]:
a.norm(2)

tensor(2.8284)

In [352]:
b.norm(2)

tensor(2.8284)

In [353]:
a.norm(1,dim=0)

tensor(8.)

In [354]:
b.norm(1,dim=0) 

tensor([2., 2., 2., 2.])

In [356]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [355]:
c.norm(1,dim=0) # 把0维度最后会消掉

tensor([[2., 2.],
        [2., 2.]])

[
    [[1]]
    [[1]]
]

这两个位置相加

### 排序

In [357]:
res = torch.arange(8).view(2,4)

In [362]:
res

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [358]:
res.argmax(),res.argmin()

(tensor(7), tensor(0))

In [363]:
res.argmax(dim=1) # 当然你也可以设置维度，返回的是元素的位置，不是具体的值了

tensor([3, 3])

### 最大值和最小值

In [365]:
test = torch.rand(2,3)

test.max(dim=0) # dim=0就是消掉2，返回一个shape是3的

torch.return_types.max(
values=tensor([0.8874, 0.8856, 0.8725]),
indices=tensor([1, 1, 0]))

In [367]:
test.max(dim=0,keepdim=True).values # 可以发现维度还是2，3

tensor([[0.8874, 0.8856, 0.8725]])

In [371]:
# topk

a = torch.rand(3,5)
a

tensor([[0.3170, 0.2673, 0.9839, 0.4889, 0.6655],
        [0.8522, 0.4805, 0.3176, 0.4276, 0.0217],
        [0.2843, 0.6133, 0.7434, 0.0560, 0.9626]])

In [372]:
a.topk(3,dim=1,largest=False) # 找到每行的前3个最大值

torch.return_types.topk(
values=tensor([[0.9839, 0.6655, 0.4889],
        [0.8522, 0.4805, 0.4276],
        [0.9626, 0.7434, 0.6133]]),
indices=tensor([[2, 4, 3],
        [0, 1, 3],
        [4, 2, 1]]))

In [375]:
a.kthvalue(1,dim=1) # 返回对应维度的最小值

torch.return_types.kthvalue(
values=tensor([0.2673, 0.0217, 0.0560]),
indices=tensor([1, 4, 3]))

## 比较运算

In [376]:
test = torch.rand(3,4)

In [380]:
test

tensor([[0.3471, 0.7120, 0.2535, 0.0636],
        [0.5709, 0.4324, 0.5272, 0.3198],
        [0.3665, 0.7102, 0.4018, 0.7993]])

In [377]:
test > 0

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [379]:
test < 0

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [382]:
test == test

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## where,gather

### where

In [415]:
a = torch.arange(4).view(2,2).type(torch.LongTensor)
a

tensor([[0, 1],
        [2, 3]])

In [416]:
b = torch.arange(4,8).view(2,2).type(torch.LongTensor)
b

tensor([[4, 5],
        [6, 7]])

In [417]:
# 看下where命令
# where 就是 a if 1 else b

torch.where(a>1, a, b) # a,b 的数据都要转化成float类型。不然会报错

tensor([[4, 5],
        [2, 3]])

### gather

In [418]:
# gather就是查表
# v、https://zhuanlan.zhihu.com/p/101896024
help(torch.gather)

Help on built-in function gather:

gather(...)
    gather(input, dim, index, out=None, sparse_grad=False) -> Tensor
    
    Gathers values along an axis specified by `dim`.
    
    For a 3-D tensor the output is specified by::
    
        out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
        out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
        out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2
    
    If :attr:`input` is an n-dimensional tensor with size
    :math:`(x_0, x_1..., x_{i-1}, x_i, x_{i+1}, ..., x_{n-1})`
    and ``dim = i``, then :attr:`index` must be an :math:`n`-dimensional tensor with
    size :math:`(x_0, x_1, ..., x_{i-1}, y, x_{i+1}, ..., x_{n-1})` where :math:`y \geq 1`
    and :attr:`out` will have the same size as :attr:`index`.
    
    Args:
        input (Tensor): the source tensor
        dim (int): the axis along which to index
        index (LongTensor): the indices of elements to gather
        out (Tensor, optional): the 

In [420]:
a = torch.randint(1,10,(2,2))
a

tensor([[4, 5],
        [2, 3]])

In [431]:
b = torch.randint(0,2,(2,2))
b

tensor([[0, 0],
        [1, 0]])

In [433]:
torch.gather(a, 1, b) # dim为1表示按不同列索引，0表示4，1对应3

tensor([[4, 4],
        [3, 2]])

In [435]:
torch.gather(a, 0, b)

tensor([[4, 5],
        [2, 5]])

In [437]:
# 举个实际的例子

a = torch.randn(4, 10) # randn生成正太分布的数据
a # 例如神经网络对4张照片的概率输出

tensor([[ 0.1024,  0.6968,  1.0233, -0.5221,  1.0193, -0.5163, -0.3523, -0.2783,
          0.6183, -0.2060],
        [ 2.4978, -0.2458,  2.2695, -1.7554, -2.6681, -0.9304,  0.4501,  0.5302,
          0.3926, -0.1445],
        [-0.2548,  0.5078, -0.7320, -0.8752,  1.8231,  0.9859,  0.6047,  1.4945,
          0.9100, -0.4755],
        [ 1.1922, -0.1419, -0.5319,  1.3735, -0.7563,  0.4903, -0.7779, -0.4317,
          0.4654, -0.3214]])

In [439]:
res = a.topk(dim=1, k=1) # dim=1表示找到不同列的最大值，也就是每一行的最大值
res

torch.return_types.topk(
values=tensor([[1.0233],
        [2.4978],
        [1.8231],
        [1.3735]]),
indices=tensor([[2],
        [0],
        [4],
        [3]]))

# 使用torch完成Minist手写数据集

In [46]:
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim

In [48]:
import torchvision

from matplotlib import pyplot as plt

In [49]:
#加载数据集

In [60]:
batch_size = 500

train_loader = torch.utils.data.DataLoader(
    torchvision.datasets.MNIST('mnist data', train=True, download=True, transform=torchvision.transforms.Compose(
        [torchvision.transforms.ToTensor(),torchvision.transforms.Normalize((0.13,),(0.3,))]
    )),
    batch_size=batch_size,
    shuffle=True,
)

In [61]:
test_loader = torch.utils.data.DataLoader(
    torchvision.datasets.MNIST('mnist data', train=False, download=True, transform=torchvision.transforms.Compose(
        [torchvision.transforms.ToTensor(),torchvision.transforms.Normalize((0.13,),(0.3,))]
    )),
    batch_size=batch_size,
    shuffle=False,
)

In [71]:
i,j = next(iter(train_loader))

In [73]:
i.shape
# 每个batch有500个数据

torch.Size([500, 1, 28, 28])

In [74]:
j.shape

torch.Size([500])

In [78]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # 一共有三层网络，输入是28*28
        # 第二层是256
        # 第三层是64
        # 最后输出是10，因为有0-9个数字。第二层和第三层的神经元数都是自己设定的
        self.func1 = nn.Linear(28*28, 256)
        self.func2 = nn.Linear(256, 64)
        self.func3 = nn.Linear(64, 10)
        
    def forward(self, x):
        # x:[batch, 1,28,28]
        # h1 = relu(xw1+b1)
        x = F.relu(self.func1(x))
        x = F.relu(self.func2(x))
        x = self.func3(x)
        
        return x

In [80]:
net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum = 0.9)

for epoch in range(3): # 对数据集，迭代3遍
    for batch_index, (x,y) in enumerate(train_loader): # 开始对数据集的每个batch迭代第一遍
        print(x.shape,y.shape)
        x = x.view(x.size(0), 28*28)
        out = net(x)
        y_onehot = one_hot(y)
        loss = F.mes_loss(out, y_onehot)
        
        loss.backward()
        
        optimizer.step()
        
        if batch_inde % 10 == 0:
            print(loss)

torch.Size([500, 1, 28, 28]) torch.Size([500])


NameError: name 'one_hot' is not defined