# 环境配置

## 安装conda

In [1]:
# https://blog.csdn.net/weixin_43840215/article/details/89599559
!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

--2020-08-18 20:22:58--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
正在解析主机 repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c84f, ...
正在连接 repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [跟随至新的 URL]
--2020-08-18 20:23:02--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
正在解析主机 repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
正在连接 repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：93052469 (89M) [application/x-sh]
正在保存至: “Miniconda3-latest-Linux-x86_64.sh”

16% [=====>                                 ] 15,456,713   246KB/s 剩余 3m 48s   ^C


In [ ]:
!chmod 777 Miniconda3-latest-Linux-x86_64.sh
!sh Miniconda3-latest-Linux-x86_64.sh

In [6]:
# 上面链接都是https的。然而我在下载的时候报错了。应该把s删掉
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
!conda config --add channels http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
!conda config --set show_channel_urls yes 
!conda config --get channels

/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令
/bin/bash: conda: 未找到命令


In [ ]:
# https://blog.csdn.net/zzq060143/article/details/88042075
# 请仔细参考这个，添加镜像
!conda install pytorch torchvision cudatoolkit=10.2

In [23]:
import sys

sys.executable

'/root/miniconda3/bin/python'

In [3]:
import torch

In [ ]:
# 由于我是使用conda安装的，默认使用的是conda的base环境。
# 所以其他环境是使用不了torch的
# 先要激活conda环境，并且退出当前的virtualenv

!deactivate # 在当前环境直接输入这个指令即可
!source miniconda3/bin/activate
!conda jupyter notebook

In [2]:
import pandas as pd

import numpy as np

In [24]:
data = pd.DataFrame(np.arange(8).reshape(4,2),columns=['a','b'])

In [12]:
test = pd.DataFrame(np.arange(4,12).reshape(4,2),columns=['c','d'])

In [18]:
# 可以使用这种方法同时修改训练集和测试集
all_data = [data, test]
for i in all_data:
    i.iloc[:,1] = np.arange(4)

In [30]:
# 查看电脑的显卡能不能使用
torch.cuda.is_available()

False

# 两个重要函数

In [32]:
# dir(torch) dir可以查看有哪些可用的函数

In [33]:
# help(torch.cuda) help告诉我们如何使用这个函数

# torch的学习

In [4]:
# torch类型数据
# numpy类型数据

np_data = np.arange(8).reshape(2,4)
np_data

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## 数据类型

在torch中，如果是一个数字，就是0维，**在torch中没有string类型的数据**。如果要表示字符串类型，可以使用one-hot方法

然而在实际的生活中，英语单词有上万多个，我们单独靠one-hot，会使得矩阵非常稀疏。而且不能表达出单词的近似程度。

所以one-hot编码是有缺陷的，所以人们开发出来其他的方式来编码，编码叫Embedding， 里面有w2v， glove方式

floattensor  32

doubletensor 64

longtensor 64

inttensor 32

bytetensor 8

In [81]:
a = torch.randn(2,3)
a.type() # 返回的是具体的数据类型

'torch.FloatTensor'

In [82]:
# 返回的是基本的数据类型
type(a)

torch.Tensor

In [83]:
# 判断诗句类型是不是一致
isinstance(a, torch.FloatTensor)

True

In [ ]:
# 将数据放到GPU的时候数据类型但是又会发生变化

isinstance(data, torch.cuda.FloatTensor)

data.cuda() # 将数据放到GPU上

isinstance(data, torch.cuda.FloatTensor)

0维的有什么用呢？通常loss就是0维的，也就是标量

In [86]:
# 纬度为0的标量，维度为0就是标量
torch.tensor(1.)

tensor(1.)

In [87]:
torch.tensor(1.).item()

1.0

In [88]:
torch.tensor(1.).shape

torch.Size([])

In [89]:
torch.tensor(1.).dim()

0

维度为1的张量有什么用呢？

在神经元中，我们通常要设置偏置。ax+b中b就是。我们用一维张量表示

In [92]:
# 1 dim []
torch.tensor([1])

tensor([1])

In [94]:
torch.tensor([1]).shape

torch.Size([1])

In [95]:
torch.tensor([1,1]).item()

ValueError: only one element tensors can be converted to Python scalars

In [97]:
# 2 dim [[],[]],多个列表嵌套就是2维

a = torch.FloatTensor(2,3)
a

tensor([[-1.0798e-24,  4.5891e-41, -1.5148e+00],
        [ 3.0624e-41,         nan,  0.0000e+00]])

In [103]:
b = torch.FloatTensor(1,3) # 注意这是随机生成的
b

tensor([[-1.0798e-24,  4.5891e-41, -1.3108e+00]])

In [106]:
# 3 dim [[[]],[[]]]
# 3 dim有什么用呢？他们的使用场景非常广泛
# 比如在nlp中，一句话有10个单词，每个单词用向量表示这句话就可以用2维tensor表示[10, 100]/假如每个单词用100个表示
# 假如现在有20句话，用3 dim表示[20,10,100]
c = torch.FloatTensor(1,2,3)
c

tensor([[[-1.0798e-24,  4.5891e-41, -1.5225e+00],
         [ 3.0624e-41,  4.4842e-44,  0.0000e+00]]])

In [107]:
c[0]

tensor([[-1.0798e-24,  4.5891e-41, -1.5225e+00],
        [ 3.0624e-41,  4.4842e-44,  0.0000e+00]])

In [109]:
c[0][0]

tensor([-1.0798e-24,  4.5891e-41, -1.5225e+00])

In [110]:
# 更高维 4dim，5dim
# [2,3,29,29]
# 上面2表示照片数量，3表示每个照片颜色通道RGB，29*29表示长宽
# 注意一个维度，只能用来描述一种特征

## 创建tensor

In [ ]:
# 未初始化的tensor，不要直接使用未初始化的数据，输入到其他地方
# 未初始化只是为了申请内存，然后赋值给他。
# 如果直接将未初始化的数据喂到其他地方。因为值是随机的。有些值是无穷大。容易出现问题

torch.FloatTensor(2,2,2) # 未初始化的数据，其内部的值是随机的

In [111]:
# 随机初始化
torch.rand(3,3) # 初始化的值是在0-1之间

tensor([[0.8526, 0.3177, 0.6964],
        [0.0450, 0.3220, 0.9346],
        [0.5983, 0.3297, 0.9744]])

In [114]:
a = torch.rand(3,3,3)
c = torch.rand_like(a) # 读取一个tensor的shape，然后传给rand like。like相似
c

tensor([[[0.4837, 0.7445, 0.2592],
         [0.3884, 0.1026, 0.6049],
         [0.4994, 0.7637, 0.4178]],

        [[0.3952, 0.8937, 0.4947],
         [0.4957, 0.4705, 0.9129],
         [0.7484, 0.5479, 0.8227]],

        [[0.6375, 0.6115, 0.6347],
         [0.4693, 0.2609, 0.5884],
         [0.2203, 0.5070, 0.4755]]])

In [116]:
torch.randint(1,10,[2,2]) # 在最大和最小值区间生成随机数，第三个参数是指定shape，以列表的形式传入，不包括最大值10

tensor([[2, 9],
        [3, 9]])

In [118]:
torch.randn(3,3) # 生成一个正太分布的数据。

tensor([[-0.8897,  1.5054,  0.1210],
        [-0.1361,  0.3104, -0.7207],
        [ 1.0253, -1.2426,  0.5322]])

In [126]:
torch.full([2,3],0.0,) # 好像只能生成float类型的数据

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [129]:
torch.full([],3.) # 创建一个标量

tensor(3.)

In [134]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [137]:
torch.linspace(0,10,10) # 等份切

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [138]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [139]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [140]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [141]:
torch.randperm(10) # 生成一个随机的序列

tensor([2, 4, 3, 1, 8, 0, 7, 6, 9, 5])

## 索引和切片

In [145]:
data = torch.rand(2,3,2)
data

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]],

        [[0.7212, 0.0430],
         [0.5839, 0.6931],
         [0.6613, 0.2377]]])

In [146]:
data[0] # 索引的是第0个3，2

tensor([[0.9975, 0.8395],
        [0.4927, 0.9900],
        [0.3013, 0.9192]])

In [149]:
data[0,0]

tensor([0.9975, 0.8395])

In [148]:
data[0,0,1]

tensor(0.8395)

In [147]:
for each in data: # 居然可以遍历
    print(each)

tensor([[0.9975, 0.8395],
        [0.4927, 0.9900],
        [0.3013, 0.9192]])
tensor([[0.7212, 0.0430],
        [0.5839, 0.6931],
        [0.6613, 0.2377]])


In [153]:
# 切片
data[:1]

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]]])

In [154]:
data[:1].dim() # 依旧是三维的 # 这里是对第一个通道索引

3

In [157]:
data[:1,:1] # 还可以对第二个通道索引

tensor([[[0.9975, 0.8395]]])

In [158]:
data[:1,-1:] # -1开始表示只选取末尾

tensor([[[0.3013, 0.9192]]])

In [160]:
data[:1:2,:,:] # 甚至可以隔行采样

tensor([[[0.9975, 0.8395],
         [0.4927, 0.9900],
         [0.3013, 0.9192]]])

In [162]:
data = torch.rand(3,3,3)
data

tensor([[[0.9250, 0.9249, 0.6874],
         [0.3065, 0.2696, 0.8503],
         [0.0577, 0.7079, 0.6500]],

        [[0.1635, 0.2214, 0.2830],
         [0.1326, 0.0176, 0.5144],
         [0.7082, 0.1147, 0.5520]],

        [[0.0726, 0.4157, 0.1398],
         [0.6775, 0.5979, 0.3828],
         [0.5380, 0.3950, 0.5863]]])

In [163]:
data.index_select(0,[0,2])

TypeError: index_select() received an invalid combination of arguments - got (int, list), but expected one of:
 * (name dim, Tensor index)
      didn't match because some of the arguments have invalid types: (int, list)
 * (int dim, Tensor index)
      didn't match because some of the arguments have invalid types: (int, list)


In [165]:
help(torch.index_select)

Help on built-in function index_select:

index_select(...)
    index_select(input, dim, index, out=None) -> Tensor
    
    Returns a new tensor which indexes the :attr:`input` tensor along dimension
    :attr:`dim` using the entries in :attr:`index` which is a `LongTensor`.
    
    The returned tensor has the same number of dimensions as the original tensor
    (:attr:`input`).  The :attr:`dim`\ th dimension has the same size as the length
    of :attr:`index`; other dimensions have the same size as in the original tensor.
    
    .. note:: The returned tensor does **not** use the same storage as the original
              tensor.  If :attr:`out` has a different shape than expected, we
              silently change it to the correct shape, reallocating the underlying
              storage if necessary.
    
    Args:
        input (Tensor): the input tensor.
        dim (int): the dimension in which we index
        index (LongTensor): the 1-D tensor containing the indices to index


## TODO

看pytorch基础教程，第19课时。完成上面最近的select_index

## 将array转化成tensor

In [5]:
torch_data = torch.from_numpy(np_data)
torch_data # 将np数据转化成tensor

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [6]:
type(torch_data)

torch.Tensor

## 将tensor转化成array

In [7]:
tensor_to_array = torch_data.numpy()

## 一些常用函数

In [23]:
data1 = [1,9]
data2 = [[1,2],[3,4]]

In [24]:
torch.mean(data1)

TypeError: mean(): argument 'input' (position 1) must be Tensor, not list

In [25]:
np.mean(data1)

5.0

In [26]:
# 在torch和numpy中，前者最好先将数据转化成tensor的形式，后者最好转化成array的形式
# 这样转换后，才好通过运算
array1 = np.array(data1)
array2 = np.array(data2)
tensor1 = torch.FloatTensor(data1)
tensor2 = torch.FloatTensor(data2)

In [27]:
torch.mean(data)

tensor(3.)

In [28]:
torch.sin(data)

tensor([ 0.8415,  0.4121, -0.8415,  0.1411])

In [29]:
torch.abs(data)

tensor([1., 9., 1., 3.])

## 矩阵相乘

In [30]:
array2.dot(array2) # 矩阵的乘法

array([[ 7, 10],
       [15, 22]])

In [31]:
array2.dot(array1)

array([19, 39])

In [32]:
array1*array2 # 甚至可以按位运算

array([[ 1, 18],
       [ 3, 36]])

In [36]:
tensor1

tensor([1., 9.])

In [42]:
tensor2

tensor([[1., 2.],
        [3., 4.]])

In [44]:
tensor1.dot(tensor1) # 1*1+9*9

tensor(82.)

# 使用torch完成Minist手写数据集

In [46]:
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim

In [48]:
import torchvision

from matplotlib import pyplot as plt

In [49]:
#加载数据集

In [60]:
batch_size = 500

train_loader = torch.utils.data.DataLoader(
    torchvision.datasets.MNIST('mnist data', train=True, download=True, transform=torchvision.transforms.Compose(
        [torchvision.transforms.ToTensor(),torchvision.transforms.Normalize((0.13,),(0.3,))]
    )),
    batch_size=batch_size,
    shuffle=True,
)

In [61]:
test_loader = torch.utils.data.DataLoader(
    torchvision.datasets.MNIST('mnist data', train=False, download=True, transform=torchvision.transforms.Compose(
        [torchvision.transforms.ToTensor(),torchvision.transforms.Normalize((0.13,),(0.3,))]
    )),
    batch_size=batch_size,
    shuffle=False,
)

In [71]:
i,j = next(iter(train_loader))

In [73]:
i.shape
# 每个batch有500个数据

torch.Size([500, 1, 28, 28])

In [74]:
j.shape

torch.Size([500])

In [78]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # 一共有三层网络，输入是28*28
        # 第二层是256
        # 第三层是64
        # 最后输出是10，因为有0-9个数字。第二层和第三层的神经元数都是自己设定的
        self.func1 = nn.Linear(28*28, 256)
        self.func2 = nn.Linear(256, 64)
        self.func3 = nn.Linear(64, 10)
        
    def forward(self, x):
        # x:[batch, 1,28,28]
        # h1 = relu(xw1+b1)
        x = F.relu(self.func1(x))
        x = F.relu(self.func2(x))
        x = self.func3(x)
        
        return x

In [80]:
net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum = 0.9)

for epoch in range(3): # 对数据集，迭代3遍
    for batch_index, (x,y) in enumerate(train_loader): # 开始对数据集的每个batch迭代第一遍
        print(x.shape,y.shape)
        x = x.view(x.size(0), 28*28)
        out = net(x)
        y_onehot = one_hot(y)
        loss = F.mes_loss(out, y_onehot)
        
        loss.backward()
        
        optimizer.step()
        
        if batch_inde % 10 == 0:
            print(loss)

torch.Size([500, 1, 28, 28]) torch.Size([500])


NameError: name 'one_hot' is not defined